# PLAY1 A PLAY TO DEPLOY APACHE on Ubuntu Instance
- name: configure apache on ubuntu instances
  hosts: ubuntuclients
  tasks: 
    - name: Update all packages to their latest version
      apt: # Module 1
        name: "*"
        state: latest
    - name: Install apache httpd  (state=present is optional)
      apt:
        name: apache2
        state: present
    - name: Start service httpd, if not started #systemctl start httpd
      ansible.builtin.service: # Mododule 2
        name: apache2
        state: started
    - name: Enable service httpd, and not touch the state #systemctl enable httpd
      ansible.builtin.service:
        name: apache2
        enabled: yes
    - name: Copy index file from controller to the clients
      ansible.builtin.copy: # Module 3
        src: /home/ubuntu/index.html #on the controller
        dest: /var/www/html/ # Clients
# PLAY2 WRITE A PLAY TO INSTALL GIT
- name: Install GIT on the Ubuntu clients.  #PLAY 2
  hosts: ubuntuclients
  tasks:
    - name: Update repository
      apt_repository:
        repo: 'ppa:git-core/ppa'
        state: present
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes